### ISSUE TITLE
Improve Sliders responsiveness

### ISSUE THREAD

**Issue by eleriaqueen** [vE5li/korangar#33] opened 2023-07-24 07:48 UTC
Currently when moving a Slider to the right, the associated value only updates after a considerable distance traveled which feels unresponsive. (Can be experienced in Theme Viewer)

**Comment by vE5li** [comment] 2023-07-24 16:29
The values are not displayed with all of their decimal places, is it possible that that gave you the impression of being unresponsive?

Because the values will start changing as soon as you move even by 1 pixel

**Comment by eleriaqueen** [comment] 2023-07-24 20:03
The unresponsive part is that sliding to the left responds much quicker than to the right.

**Comment by vE5li** [comment] 2023-07-25 19:42
Since neither you nor me are able to reproduce this I will close this issue. Feel free to reopen if this should happen again.

**Closed by vE5li** 2023-07-25 19:42 UTC
Labels: enhancement, question
